# Generated by Django 5.2 on 2025-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_rename_date_ajout_produit_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
